### ISSUE TITLE
Feature-Request: Less interwoven Channel / Stream URLs 

### ISSUE THREAD

**Issue by noestreich** [Mauricevb/NPO-Live-Apple-TV-4#1]
Great work. 

Your TV-App could be a great template for other countries livestream-needs. 
Right now, the Stream URLs are quite deeply interwoven if i understand your code corecct. You are working with regex und base-URLs. 

It would be great if you could handle the URLs modular, maybe in a single extra file. So it would be much easier to replace the NL-Streams with their german, italien or swedish counterparts for example.

**Comment by Mauricevb** [comment]
I think you're right about the fact that the URL's are too interwoven in the application. It's a good idea to separate the stream list from the "core".

For now you can add channels like this:
```
Channel(title: "Channel name", url: NSURL(string: "http://...")!)
```
Make sure the images assets have the same filename as the channel title.

Making a TV guide to show what's live now has a higher priority than this, but feel free to make a pull request.

**Comment by noestreich** [comment]
great. small correction. second block ought be:
    channel.streamUrl = url
    self.performSegueWithIdentifier("streamChannel", sender: channel)

**Comment by Mauricevb** [comment]
Look awesome!
