### ISSUE TITLE
Run on Swift 3

### ISSUE THREAD

**Issue by kerkenit** [Mauricevb/NPO-Live-Apple-TV-4#12]
I'm unable to run it on my Apple TV.
It's say's I've to covert it to Swift 3. Otherwise it won't run. But i'm unable to convert it.
I's give a bunch of compile errors. I'm a developer, but Swift is not in my vocabularia

**Comment by sjogro** [comment]
Swift 4 conversion is available, same story. Please update! I would love to use this app, but can't currently.

**Comment by hollanderbart** [comment]
I forked and fixed the project. You can find it on my repo: https://github.com/hollanderbart/NPO-Live-Apple-TV-4.

**Comment by hollanderbart** [comment]
I fixed the project and maintaining it now. https://github.com/hollanderbart/NPO-Live

**Comment by sjogro** [comment]
Great news! I’ll check it out this weekend

**Comment by BasThomas** [comment]
Thanks @hollanderbart!
