### ISSUE TITLE
Design update to match tvOS

### ISSUE THREAD

**Issue by iAmRenzo** [Mauricevb/NPO-Live-Apple-TV-4#2]
Great initiative for starters, but if I may say so: the design not so much.

I would suggest a more streamlined design matching the Apple TV.
Separate the three NPO main channels and the other digital streams.

**Comment by Mauricevb** [comment]
We haven’t worked on the design yet. In the first instance we wanted to build the core functionality. Now this is finished, we will continue improving the app.
The next task on our todo list is creating a Apple worthy design :)

**Comment by iAmRenzo** [comment]
If you need any help of ideas... I'm not a good programmer but I do have a good eye for design.

**Comment by Mauricevb** [comment]
![simulator screen shot 24 nov 2015 21 19 51](https://cloud.githubusercontent.com/assets/2742292/11379570/5d96aa82-92f1-11e5-9f05-e9faad5ccb57.png)

**Comment by amphorainteractive** [comment]
That image looks good! If it will display the current show title under the logo would be very nice

**Comment by Mauricevb** [comment]
Yep, that's the idea. At the moment I don't have any idea how I can get that data, but I'll find a way.

I'm still not statisfied with the design above. I think it can be better. It's too flat and there is too much white.

What do you think?

**Comment by iAmRenzo** [comment]
The name of the current programm would be great. It is displayed on the website of NPO.nl during a live broadcast. But I do not know how to retrieve it.
