### ISSUE TITLE
Notificiation for update

### ISSUE THREAD

**Issue by iAmRenzo** [Mauricevb/NPO-Live-Apple-TV-4#5]
I believe there is a notificiation system within tvOS. Would it be easy to make use of this if there is an update for the app?

**Comment by Mauricevb** [comment]
At the moment, you can't use push notifications. But we can check for updates every time you open the NPO Live app. We can use the [Github API](https://developer.github.com/v3/repos/releases/) for this.

I hope other developers will contribute to this project and will create some pull requests ;)
