### ISSUE TITLE
NPO live not working any more since 28 or 29 MArch 2016

### ISSUE THREAD

**Issue by Nikowal** [Mauricevb/NPO-Live-Apple-TV-4#8]
love the app. been great all the while, however the NPO live and uitzendinggemist stopped working since 28 or 29 March 2016. 
After selecting the apps the screen turns white and remains that way.

**Comment by Wildeweg** [comment]
Same here. NPO probably changed something.

**Comment by hollanderbart** [comment]
I forked and fixed the project. You can find it on my repo: https://github.com/hollanderbart/NPO-Live-Apple-TV-4.

**Comment by hollanderbart** [comment]
I fixed the project and maintaining it now. https://github.com/hollanderbart/NPO-Live
